// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InvoicesUIClient is the client API for InvoicesUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvoicesUIClient interface {
	// ListEngineSpecs returns a list of Invoicing Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (InvoicesUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type invoicesUIClient struct {
	cc grpc.ClientConnInterface
}

func NewInvoicesUIClient(cc grpc.ClientConnInterface) InvoicesUIClient {
	return &invoicesUIClient{cc}
}

func (c *invoicesUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (InvoicesUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &InvoicesUI_ServiceDesc.Streams[0], "/v1.InvoicesUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &invoicesUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InvoicesUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type invoicesUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *invoicesUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *invoicesUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.InvoicesUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoicesUIServer is the server API for InvoicesUI service.
// All implementations must embed UnimplementedInvoicesUIServer
// for forward compatibility
type InvoicesUIServer interface {
	// ListEngineSpecs returns a list of Invoicing Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, InvoicesUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedInvoicesUIServer()
}

// UnimplementedInvoicesUIServer must be embedded to have forward compatible implementations.
type UnimplementedInvoicesUIServer struct {
}

func (UnimplementedInvoicesUIServer) ListEngineSpecs(*ListEngineSpecsRequest, InvoicesUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedInvoicesUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedInvoicesUIServer) mustEmbedUnimplementedInvoicesUIServer() {}

// UnsafeInvoicesUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvoicesUIServer will
// result in compilation errors.
type UnsafeInvoicesUIServer interface {
	mustEmbedUnimplementedInvoicesUIServer()
}

func RegisterInvoicesUIServer(s grpc.ServiceRegistrar, srv InvoicesUIServer) {
	s.RegisterService(&InvoicesUI_ServiceDesc, srv)
}

func _InvoicesUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InvoicesUIServer).ListEngineSpecs(m, &invoicesUIListEngineSpecsServer{stream})
}

type InvoicesUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type invoicesUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *invoicesUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _InvoicesUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoicesUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.InvoicesUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoicesUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvoicesUI_ServiceDesc is the grpc.ServiceDesc for InvoicesUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvoicesUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.InvoicesUI",
	HandlerType: (*InvoicesUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _InvoicesUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _InvoicesUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "invoices-ui.proto",
}
